
param32chlist = {
    "Current (A)" :     1, 
    "dI/dV (V)"   :     2, 
    "d2I/dV2" :     4, 
    "ADC0 (V)"    :     8, 
    "ADC1 (V)"    :     16,
    "ADC2 (V)"    :     32,
    "ADC3 (V)"    :     64,
    "Freq. Shift (Hz)"       :    128, 
    "Damping (V)":      256, 
    "Amplitude (V)":    512, 
    "dI/dV Y (V)":      1024,
    "d2I/dV2 Y (V)":    2048,
    "Top DAC0 (Å)":     4096,
    "BIAS DAC (V)":     8192,
    "Not used":     16384,
    "ADC4 (V)":         32768,
    "ADC5 (V)":         65536,
    "ADC6 (V)":         131072,
    "ADC7 (V)":         262144,
}

param30chlist = {
    "Current (A)" : 1, 
    "dI/dV (V)"   : 2, 
    "d2I/dV2 (V)" : 4, 
    "ADC0 (V)"    : 8, 
    "ADC1 (V)"    : 16,
    "ADC2 (V)"    : 32,
    "ADC3 (V)"    : 64,
    "NA0"       : 128, 
    "NA1"       : 256, 
    "NA2"      : 512, 
    "di_q (V)"    : 1024,
    "di2_q (V)"   : 2048,
    "Top DAC0 (Å)": 4096,
}

dat32chlist = {
    "Z (m)":            1,
    "Current (A)":      2,
    "ADC1 (V)":         4,
    "ADC2 (V)":         8,
    "ADC3 (V)":         16,
    "dI/dV (V)":        32,
    "d2I/dV2 (V)":      64,
    "Freq. Shift (Hz)": 128, 
    "Damping (V)":      256, 
    "Amplitude (V)":    512, 
}

dacUnits = {
        "Bias (V)":         "V",
        "Z (nm)":         "ADCZ",
        "X (nm)":            "V",
        "unknown":       "",
        "Current (A)":      "ADCI",
        "dI/dV (V)":        "ADCV",
        "d2I/dV2 (V)" :     "ADCV", 
        "ADC0 (V)"    :     "ADCV", 
        "ADC1 (V)"    :     "ADCV",
        "ADC2 (V)"    :     "ADCV",
        "ADC3 (V)"    :     "ADCV",
        "Freq. Shift (Hz)"       :    "Hz", 
        "Damping (V)":      "ADCV", 
        "Amplitude (V)":    "ADCV", 
        "dI/dV Y (V)":      "ADCV",
        "d2I/dV2 Y (V)":    "ADCV",
        "Top DAC0 (Å)":     "ADCZ",
        "BIAS DAC (V)":     "ADCV",
        "Not used":     "",
        "ADC4 (V)":         "ADCV",
        "ADC5 (V)":         "ADCV",
        "ADC6 (V)":         "ADCV",
        "ADC7 (V)":         "ADCV",
    }
